In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\User\AppData\Local\Temp\ipykernel_9828\800486908.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df=pd.read_csv("insurance_data.csv")
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

In [4]:
len(X_train)

22

In [5]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [6]:
X_train_scaled.head()

     age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1

In [7]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

C:\Users\User\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [8]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [9]:
model.fit(X_train_scaled,y_train,epochs=5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 880ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 13/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7068
Epoch 14/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7065
Epoch 15/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.7061
Epoch 16/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7057
Epoch 17/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7054
Epoch 18/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7050
Epoch 19/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7046
Epoch 20/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7043
Epoch 21/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7039
Epoch 22/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 23/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7032
Epoch 24/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7028
Epoch 25/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7025
Epoch 26/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7021
Epoch 27/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7017
Epoch 28/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7014
Epoch 29/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7010
Epoch 30/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7007
Epoch 31/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7003
Epoch 32/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7000
Epoch 33/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6996
Epoch 34/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6993
Epoch 35/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6989
Epoch 36/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6986
Epoch 37/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6982
Epoch 38/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6979
Epoch 39/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6975
Epoch 40/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6972
Epoch 41/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6969
Epoch 42/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6965
Epoch 43/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6962
Epoch 44/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6958
Epoch 45/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6955
Epoch 46/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6952
Epoch 47/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6948
Epoch 48/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6945
Epoch 49/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6942
Epoch 50/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6938
Epoch 51/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6935
Epoch 52/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6932
Epoch 53/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6928
Epoch 54/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 55/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6922
Epoch 56/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6918
Epoch 57/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6915
Epoch 58/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6912
Epoch 59/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6909
Epoch 60/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6906
Epoch 61/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6902
Epoch 62/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 63/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6896
Epoch 64/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6893
Epoch 65/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6890
Epoch 66/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6886
Epoch 67/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6883
Epoch 68/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6880
Epoch 69/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6877
Epoch 70/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6874
Epoch 71/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 72/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6868
Epoch 73/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6865
Epoch 74/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6862
Epoch 75/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6859
Epoch 76/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 77/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6853
Epoch 78/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6849
Epoch 79/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6846
Epoch 80/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6843
Epoch 81/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6840
Epoch 82/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6838
Epoch 83/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6835
Epoch 84/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6832
Epoch 85/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6829
Epoch 86/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6826
Epoch 87/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6823
Epoch 88/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6820
Epoch 89/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6817
Epoch 90/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6814
Epoch 91/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6811
Epoch 92/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6808
Epoch 93/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6805
Epoch 94/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6803
Epoch 95/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6800
Epoch 96/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6797
Epoch 97/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6794
Epoch 98/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6791
Epoch 99/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6788
Epoch 100/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6786
Epoch 101/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6783
Epoch 102/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6780
Epoch 103/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6777
Epoch 104/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6775
Epoch 105/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6772
Epoch 106/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6769
Epoch 107/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6766
Epoch 108/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6764
Epoch 109/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6761
Epoch 110/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6758
Epoch 111/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6756
Epoch 112/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.6753
Epoch 113/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6750
Epoch 114/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6748
Epoch 115/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6745
Epoch 116/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6742
Epoch 117/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6740
Epoch 118/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6737
Epoch 119/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6735
Epoch 120/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6732
Epoch 121/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6730
Epoch 122/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6727
Epoch 123/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6724
Epoch 124/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5000 - loss: 0.6722
Epoch 125/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6719
Epoch 126/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6717
Epoch 127/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6714
Epoch 128/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6712
Epoch 129/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6709
Epoch 130/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6707
Epoch 131/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6704
Epoch 132/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6702
Epoch 133/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6699
Epoch 134/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6697
Epoch 135/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6695
Epoch 136/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6692
Epoch 137/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6690
Epoch 138/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6687
Epoch 139/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6685
Epoch 140/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6683
Epoch 141/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6680
Epoch 142/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6678
Epoch 143/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6675
Epoch 144/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6673
Epoch 145/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6671
Epoch 146/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6668
Epoch 147/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6666
Epoch 148/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6664
Epoch 149/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6661
Epoch 150/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6659
Epoch 151/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6657
Epoch 152/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.6655
Epoch 153/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6652
Epoch 154/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6650
Epoch 155/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6648
Epoch 156/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6646
Epoch 157/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6643
Epoch 158/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6641
Epoch 159/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 0.6639
Epoch 160/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6637
Epoch 161/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6635
Epoch 162/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6632
Epoch 163/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6630
Epoch 164/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6628
Epoch 165/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6626
Epoch 166/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.6624
Epoch 167/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6622
Epoch 168/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6620
Epoch 169/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6617
Epoch 170/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6615
Epoch 171/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6613
Epoch 172/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6611
Epoch 173/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6609
Epoch 174/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6607
Epoch 175/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6605
Epoch 176/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6603
Epoch 177/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5455 - loss: 0.6601
Epoch 178/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6599
Epoch 179/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5455 - loss: 0.6597
Epoch 180/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6595
Epoch 181/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6593
Epoch 182/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6591
Epoch 183/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6589
Epoch 184/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6587
Epoch 185/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6585
Epoch 186/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6583
Epoch 187/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6581
Epoch 188/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6579
Epoch 189/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6577
Epoch 190/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5455 - loss: 0.6575
Epoch 191/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6573
Epoch 192/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6571
Epoch 193/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6569
Epoch 194/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6568
Epoch 195/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6566
Epoch 196/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6564
Epoch 197/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6562
Epoch 198/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6560
Epoch 199/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6558
Epoch 200/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6556
Epoch 201/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6555
Epoch 202/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5455 - loss: 0.6553
Epoch 203/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6551
Epoch 204/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6549
Epoch 205/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6547
Epoch 206/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6545
Epoch 207/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6544
Epoch 208/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6542
Epoch 209/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6540
Epoch 210/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6538
Epoch 211/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6537
Epoch 212/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6535
Epoch 213/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6533
Epoch 214/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6531
Epoch 215/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6530
Epoch 216/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6528
Epoch 217/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6526
Epoch 218/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6525
Epoch 219/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6523
Epoch 220/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6521
Epoch 221/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6519
Epoch 222/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6518
Epoch 223/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5455 - loss: 0.6516
Epoch 224/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6515
Epoch 225/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6513
Epoch 226/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5455 - loss: 0.6511
Epoch 227/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6510
Epoch 228/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6508
Epoch 229/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6506
Epoch 230/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6505
Epoch 231/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6503

In [10]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 1.0000 - loss: 0.3550

[0.35497763752937317, 1.0]

In [11]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)

In [12]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [13]:
coef,intercept=model.get_weights()
coef,intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

In [14]:
def sigmoid(x):
    import math
    return (1/(1+math.exp(-x)))

In [15]:
sigmoid(15)

0.999999694097773

In [16]:
def prediction_function(age,affordibility):
    y=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(y)

In [17]:
prediction_function(0.47,1)

C:\Users\User\AppData\Local\Temp\ipykernel_9828\1219326287.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return (1/(1+math.exp(-x)))

0.7054847702382996

In [18]:
def Binary_crossentropy(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=np.array([max(i,epsilon) for i in y_predicted])
    y_predicted_new=np.array([min(i,1-epsilon) for i in y_predicted_new])
    log_loss=-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

    return log_loss

In [19]:
def sigmoid_numpy(x):
    return (1/np.exp(-x))

In [20]:
sigmoid_numpy(np.array([12,1,0]))

array([1.62754791e+05, 2.71828183e+00, 1.00000000e+00])

Gradient descent by plane python

In [21]:
def gradient_descent(age,affordibility,y_true,epochs,min_thresold):
    #output will be -> w1,w2,b
    w1=w2=1
    bias=0
    learning_rate=0.01
    n=len(age)

    for i in range(epochs):
        weighted_sum=w1*age+w2*affordibility+bias
        y_predicted=sigmoid_numpy(weighted_sum)

        loss=Binary_crossentropy(y_true,y_predicted)

        w1d=(1/n)*np.dot((y_predicted-y_true),np.transpose(age))
        w2d=(1/n)*np.dot((y_predicted-y_true),np.transpose(affordibility))

        bias_d=np.mean(y_predicted-y_true)

        w1=w1-learning_rate*w1d
        w2=w2-learning_rate*w2d
        bias=bias-learning_rate*bias_d

        print(f"Epoch:{i}, W1:{w1}, w2:{w2}, b:{bias}, loss:{loss}")

        if(loss<=min_thresold):
            break

    return w1,w2,bias

In [22]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,5000,0.5142)

Epoch:0, W1:0.9884940686445631, w2:0.9773313061086774, b:-0.027060099272117246, loss:17.26978799617044
Epoch:1, W1:0.9776972852920576, w2:0.9560912400009733, b:-0.05252704106070282, loss:17.26978799617044
Epoch:2, W1:0.9675330650429769, w2:0.9361232899921385, b:-0.07657176760090818, loss:17.26978799617044
Epoch:3, W1:0.9579367024304617, w2:0.9172954039013133, b:-0.09933881002467407, loss:17.26978799617044
Epoch:4, W1:0.948853018965161, w2:0.8994951232805822, b:-0.1209515042885419, loss:17.26978799617044
Epoch:5, W1:0.9402345682365916, w2:0.8826258744284255, b:-0.14151597336825697, loss:17.26978799617044
Epoch:6, W1:0.9320402466163019, w2:0.8666041002232072, b:-0.16112421142703168, loss:17.26978799617044
Epoch:7, W1:0.9242342039574518, w2:0.8513570133489935, b:-0.17985650339775053, loss:17.26978799617044
Epoch:8, W1:0.9167849795161126, w2:0.8368208156581939, b:-0.1977833453571908, loss:15.948102268104417
Epoch:9, W1:0.9096648092531227, w2:0.8229392719591737, b:-0.21496698483352733, loss:15.87064946452602
Epoch:10, W1:0.9028490651545582, w2:0.809662556615945, b:-0.2314626681916912, loss:15.844715026200674
Epoch:11, W1:0.8963157973934448, w2:0.7969463125051168, b:-0.24731965972424302, loss:14.493992147128516
Epoch:12, W1:0.8900453574295397, w2:0.7847508769778594, b:-0.26258208098560537, loss:13.088874807802107
Epoch:13, W1:0.8840200854127936, w2:0.7730406404069269, b:-0.2772896072483077, loss:11.668141245110354
Epoch:14, W1:0.8782240491217487, w2:0.761783510914874, b:-0.29147804940200206, loss:11.552599835878034
Epoch:15, W1:0.8726428245381527, w2:0.7509504648275789, b:-0.30517984325960595, loss:11.49641219730366
Epoch:16, W1:0.8672633103134185, w2:0.7405151668593473, b:-0.31842446346165393, loss:11.457666032712481
Epoch:17, W1:0.8620735700162323, w2:0.7304536474176593, b:-0.3312387755488611, loss:11.428081664819691
Epoch:18, W1:0.8570626973012593, w2:0.7207440270030373, b:-0.3436473369997721, loss:11.404261824706625
Epoch:19, W1:0.8522207001048066, w2:0.711366279676735, b:-0.3556726558877959, loss:11.384431181751792
Epoch:20, W1:0.8475384007255005, w2:0.70230202912341, b:-0.367335414142807, loss:11.36753210671446
Epoch:21, W1:0.8430073492383606, w2:0.6935343720552175, b:-0.37865466109210916, loss:11.352879323356621
Epoch:22, W1:0.838619748157321, w2:0.6850477246671136, b:-0.3896479819193004, loss:11.340001829539355
Epoch:23, W1:0.8343683866327022, w2:0.6768276886195366, b:-0.40033164485448236, loss:11.328561350092551
Epoch:24, W1:0.8302465827677112, w2:0.6688609336382729, b:-0.4107207302480402, loss:11.318306500379423
Epoch:25, W1:0.8262481328778999, w2:0.6611350943156545, b:-0.4208292441470975, loss:11.30904529217645
Epoch:26, W1:0.8223672667119497, w2:0.6536386790977798, b:-0.43067021856142734, loss:11.300627776782475
Epoch:27, W1:0.8185986078106493, w2:0.6463609897687761, b:-0.4402558002530933, loss:9.986484219478204
Epoch:28, W1:0.8149371383107887, w2:0.6392920500103595, b:-0.44959732959518367, loss:9.908392156190109
Epoch:29, W1:0.8113781676076257, w2:0.6324225418348886, b:-0.4587054108070378, loss:8.605486386491028
Epoch:30, W1:0.8079173043780373, w2:0.6257437488719606, b:-0.46758997467644947, loss:8.483965383392654
Epoch:31, W1:0.8045504315399765, w2:0.6192475056396449, b:-0.476260334715655, loss:8.438885180942139
Epoch:32, W1:0.8012736837851971, w2:0.6129261520574327, b:-0.48472523756128494, loss:8.408135338292132
Epoch:33, W1:0.7980834273736076, w2:0.6067724925634986, b:-0.4929929083139444, loss:8.384468812636836
Epoch:34, W1:0.7949762419208523, w2:0.6007797592875816, b:-0.501071091416735, loss:8.365295567487038
Epoch:35, W1:0.7919489039472218, w2:0.5949415788056606, b:-0.5089670875906601, loss:8.34899908153329
Epoch:36, W1:0.7889983719869249, w2:0.5892519420660044, b:-0.5166877872758892, loss:8.334818580021308
Epoch:37, W1:0.7861217730830508, w2:0.5837051771300603, b:-0.5242397009692078, loss:8.322270888880754
Epoch:38, W1:0.783316390515985, w2:0.5782959244175838, b:-0.5316289867979406, loss:8.311027430179287
Epoch:39, W1:0.7805796526322334, w2:0.5730191141847072, b:-0.5388614756278015, loss:8.300853240730213
Epoch:40, W1:0.7779091226570833, w2:0.5678699459973527, b:-0.5459426939653639, loss:8.291573694003818
Epoch:41, W1:0.7753024893887128, w2:0.5628438699913971, b:-0.552877884884181, loss:8.283054981880667
Epoch:42, W1:0.7727575586835955, w2:0.5579365697360188, b:-0.5596720271762607, loss:8.275192002348506
Epoch:43, W1:0.7702722456536466, w2:0.5531439465383052, b:-0.5663298529069367, loss:8.267900493316207
Epoch:44, W1:0.7678445675047426, w2:0.5484621050459756, b:-0.5728558635306412, loss:8.261111728735457
Epoch:45, W1:0.7654726369542497, w2:0.5438873400214006, b:-0.5792543447072181, loss:8.254768827905075
Epoch:46, W1:0.7631546561721658, w2:0.5394161241743335, b:-0.585529379942827, loss:8.248824117379549
Epoch:47, W1:0.7608889111965766, w2:0.5350450969531998, b:-0.5916848631658659, loss:8.243237201047135
Epoch:48, W1:0.7586737667794686, w2:0.5307710542056814, b:-0.5977245103363983, loss:8.237973519448964
Epoch:49, W1:0.7565076616236257, w2:0.526590938628887, b:-0.6036518701770897, loss:8.23300325502561
Epoch:50, W1:0.7543891039754644, w2:0.522501830937803, b:-0.6094703341044282, loss:8.228300487020256
Epoch:51, W1:0.7523166675422966, w2:0.5185009416881248, b:-0.6151831454308736, loss:8.223842529872645
Epoch:52, W1:0.750288987705721, w2:0.5145856036961061, b:-0.6207934079013865, loss:8.219609408691765
Epoch:53, W1:0.7483047580056883, w2:0.5107532650038508, b:-0.6263040936214314, loss:8.215583438650107
Epoch:54, W1:0.746362726872304, w2:0.507001482343597, b:-0.6317180504279009, loss:8.211748884217041
Epoch:55, W1:0.7444616945846737, w2:0.5033279150590956, b:-0.637038008749397, loss:8.208091680475654
Epoch:56, W1:0.7426005104380863, w2:0.49973031944623586, b:-0.6422665879978425, loss:8.204599203251888
Epoch:57, W1:0.7407780701026072, w2:0.4962065434786787, b:-0.6474063025294192, loss:6.84626648183295
Epoch:58, W1:0.7389933131577395, w2:0.4927545218874768, b:-0.6524595672092741, loss:6.811452597626498
Epoch:59, W1:0.7372452207892284, w2:0.48937227156654073, b:-0.6574287026112624, loss:5.465913280259705
Epoch:60, W1:0.7355328136353536, w2:0.48605788727838617, b:-0.6623159398811452, loss:4.065469426834896
Epoch:61, W1:0.7338551497711955, w2:0.4828095376369087, b:-0.6671234252891105, loss:2.6449405995820623
Epoch:62, W1:0.7322113228203808, w2:0.47962546134600686, b:-0.671853224495188, loss:2.5636840270548906
Epoch:63, W1:0.730600460184738, w2:0.4765039636747406, b:-0.6765073265490686, loss:2.5107103579389918
Epoch:64, W1:0.7290217213831179, w2:0.47344341315139266, b:-0.6810876476439741, loss:2.4706259953721528
Epoch:65, W1:0.7274742964913871, w2:0.47044223846031463, b:-0.6855960346425499, loss:2.438197797877898
Epoch:66, W1:0.7259574046762732, w2:0.46749892552680916, b:-0.6900342683912336, loss:2.410913891953776
Epoch:67, W1:0.7244702928163569, w2:0.4646120147765353, b:-0.6944040668381826, loss:2.3873511759459896
Epoch:68, W1:0.7230122342040538, w2:0.4617800985570448, b:-0.6987070879686014, loss:2.3666175545274317
Epoch:69, W1:0.7215825273229368, w2:0.4590018187100712, b:-0.7029449325701833, loss:2.3481137570556894
Epoch:70, W1:0.7201804946951997, w2:0.45627586428411526, b:-0.7071191468403574, loss:2.3314163075166174
Epoch:71, W1:0.7188054817944809, w2:0.4536009693777073, b:-0.7112312248461024, loss:2.3162140996508884
Epoch:72, W1:0.71745685601964, w2:0.45097591110448615, b:-0.7152826108462442, loss:2.302271421510803
Epoch:73, W1:0.7161340057254263, w2:0.4483995076719306, b:-0.7192747014853819, loss:2.289405141628523
Epoch:74, W1:0.714836339306286, w2:0.4458706165662078, b:-0.7232088478678831, loss:2.277469977751831
Epoch:75, W1:0.7135632843298473, w2:0.44338813283618145, b:-0.7270863575197515, loss:2.266348622292678
Epoch:76, W1:0.7123142867168777, w2:0.4409509874701488, b:-0.7309084962455776, loss:2.2559449127220326
Epoch:77, W1:0.7110888099647494, w2:0.4385581458593566, b:-0.7346764898872525, loss:2.2464076983008314
Epoch:78, W1:0.7098863344116674, w2:0.4362086063427867, b:-0.7383915259906282, loss:2.237514761826337
Epoch:79, W1:0.7087063565391137, w2:0.43390139882810747, b:-0.7420547553858611, loss:2.229130760781618
Epoch:80, W1:0.7075483883101469, w2:0.4316355834840547, b:-0.7456672936867613, loss:2.221207033334302
Epoch:81, W1:0.7064119565413627, w2:0.4294102494998483, b:-0.749230222714088, loss:2.213701581699441
Epoch:82, W1:0.7052966023064788, w2:0.42722451390756194, b:-0.7527445918473868, loss:2.206665832318826
Epoch:83, W1:0.7042018803696485, w2:0.4250775204636499, b:-0.7562114193096401, loss:0.940604700515265
Epoch:84, W1:0.7031273586467375, w2:0.42296843858610056, b:-0.759631693388708, loss:0.8487608214799209
Epoch:85, W1:0.7020726176929244, w2:0.4208964623439293, b:-0.7630063735992647, loss:0.8156592715938163
Epoch:86, W1:0.7010372502150906, w2:0.41886080949594695, b:-0.7663363917886828, loss:0.7936082466461912
Epoch:87, W1:0.7000208606075727, w2:0.4168607205759484, b:-0.7696226531900876, loss:0.7765466526414797
Epoch:88, W1:0.6990230645099454, w2:0.41489545802165717, b:-0.7728660374255878, loss:0.7625198324131471
Epoch:89, W1:0.6980434883855878, w2:0.41296430534493705, b:-0.7760673994624923, loss:0.7505659405820942
Epoch:90, W1:0.6970817691198717, w2:0.41106656634094774, b:-0.779227570525138, loss:0.7400108621507748
Epoch:91, W1:0.6961375536368827, w2:0.4092015643340703, b:-0.7823473589647852, loss:0.7305255170892374
Epoch:92, W1:0.6952104985336552, w2:0.4073686414585704, b:-0.7854275510898776, loss:0.7218919673579961
Epoch:93, W1:0.6943002697309705, w2:0.405567157972096, b:-0.7884689119588212, loss:0.7140777891230798
Epoch:94, W1:0.69340654213982, w2:0.4037964916002275, b:-0.7914721861372985, loss:0.7070204092707905
Epoch:95, W1:0.6925289993427008, w2:0.40205603691040903, b:-0.7944380984220099, loss:0.7006545727076489
Epoch:96, W1:0.6916673332889546, w2:0.4003452047136953, b:-0.7973673545326151, loss:0.6949262878269903
Epoch:97, W1:0.6908212440034128, w2:0.3986634214928432, b:-0.8002606417735443, loss:0.689600905567891
Epoch:98, W1:0.6899904393076574, w2:0.3970101288553686, b:-0.8031186296672397, loss:0.6846490104278868
Epoch:99, W1:0.6891746345532427, w2:0.39538478301027147, b:-0.8059419705603007, loss:0.6801786851309691
Epoch:100, W1:0.6883735523662701, w2:0.39378685426721016, b:-0.8087313002039158, loss:0.6759721134265686
Epoch:101, W1:0.6875869224027367, w2:0.3922158265569804, b:-0.8114872383098805, loss:0.6720043417769789
Epoch:102, W1:0.686814481114118, w2:0.3906711969722187, b:-0.814210389083428, loss:0.6682539696324127
Epoch:103, W1:0.6860559715226731, w2:0.3891524753273163, b:-0.8169013417340261, loss:0.6647024691647052
Epoch:104, W1:0.6853111430059919, w2:0.3876591837365867, b:-0.8195606709652257, loss:0.6614424907730162
Epoch:105, W1:0.6845797510903318, w2:0.38619085620978594, b:-0.8221889374445888, loss:0.6584519028207185
Epoch:106, W1:0.6838615572523138, w2:0.38474703826413564, b:-0.8247866882546602, loss:0.6556142639292284
Epoch:107, W1:0.6831563287285785, w2:0.38332728655204745, b:-0.8273544573258969, loss:0.6529184083643317
Epoch:108, W1:0.6824638383330166, w2:0.38193116850379244, b:-0.8298927658524159, loss:0.6503543425133217
Epoch:109, W1:0.6817838642812184, w2:0.3805582619844008, b:-0.8324021226913756, loss:0.6479130786325235
Epoch:110, W1:0.6811161900217987, w2:0.37920815496411736, b:-0.8348830247467576, loss:0.645586498175775
Epoch:111, W1:0.680460604074278, w2:0.3778804452017752, b:-0.8373359573382788, loss:0.6433672384643402
Epoch:112, W1:0.6798168998732156, w2:0.376574739940484, b:-0.83976139455612, loss:0.6412485979605157
Epoch:113, W1:0.6791848756183055, w2:0.37529065561506286, b:-0.8421597996021221, loss:0.6392244565069602
Epoch:114, W1:0.6785643341301655, w2:0.3740278175706777, b:-0.8445316251180673, loss:0.6372892077091165
Epoch:115, W1:0.677955082711558, w2:0.37278585979217244, b:-0.846877313501629, loss:0.6354377012494621
Epoch:116, W1:0.6773569330138021, w2:0.37156442464360906, b:-0.8491972972105412, loss:0.6336651933856452
Epoch:117, W1:0.6767697009081418, w2:0.3703631626175588, b:-0.8514919990555159, loss:0.6319673042391565
Epoch:118, W1:0.6761932063618535, w2:0.3691817320937086, b:-0.8537618324824026, loss:0.6303399807551
Epoch:119, W1:0.6756272733188824, w2:0.36801979910637106, b:-0.8560072018440629, loss:0.6287794644270455
Epoch:120, W1:0.6750717295848112, w2:0.36687703712050657, b:-0.8582285026624084, loss:0.6272822630485878
Epoch:121, W1:0.6745264067159731, w2:0.36575312681588557, b:-0.8604261218810259, loss:0.6258451258859464
Epoch:122, W1:0.6739911399125309, w2:0.36464775587903947, b:-0.8626004381087955, loss:0.6244650217717194
Epoch:123, W1:0.6734657679153524, w2:0.3635606188026643, b:-0.8647518218548841, loss:0.6231391197048474
Epoch:124, W1:0.6729501329065218, w2:0.36249141669215945, b:-0.8668806357554791, loss:0.6218647716104374
Epoch:125, W1:0.6724440804133333, w2:0.36143985707899856, b:-0.8689872347926106, loss:0.6206394969688716
Epoch:126, W1:0.6719474592156216, w2:0.3604056537406456, b:-0.8710719665053896, loss:0.6194609690692063
Epoch:127, W1:0.6714601212562916, w2:0.3593885265267418, b:-0.8731351711939792, loss:0.6183270026793558
Epoch:128, W1:0.6709819215549133, w2:0.3583882011913034, b:-0.8751771821165951, loss:0.6172355429564997
Epoch:129, W1:0.6705127181242588, w2:0.3574044092306824, b:-0.8771983256798224, loss:0.6161846554468884
Epoch:130, W1:0.6700523718896599, w2:0.35643688772705445, b:-0.8791989216225172, loss:0.6151725170456562
Epoch:131, W1:0.6696007466110736, w2:0.35548537919720863, b:-0.8811792831935545, loss:0.6141974078052425
Epoch:132, W1:0.6691577088077463, w2:0.3545496314464254, b:-0.8831397173236657, loss:0.6132577034961474
Epoch:133, W1:0.668723127685373, w2:0.35362939742723815, b:-0.8850805247916027, loss:0.6123518688365415
Epoch:134, W1:0.6682968750656533, w2:0.3527244351028842, b:-0.8870020003848521, loss:0.6114784513180963
Epoch:135, W1:0.6678788253181491, w2:0.35183450731525867, b:-0.8889044330551127, loss:0.6106360755646499
Epoch:136, W1:0.6674688552943555, w2:0.35095938165719504, b:-0.8907881060687408, loss:0.6098234381682095
Epoch:137, W1:0.6670668442638973, w2:0.35009883034890277, b:-0.8926532971523583, loss:0.609039302953577
Epoch:138, W1:0.6666726738527701, w2:0.3492526301184005, b:-0.8945002786338089, loss:0.6082824966287084
Epoch:139, W1:0.6662862279835481, w2:0.34842056208579103, b:-0.8963293175786413, loss:0.607551904782942
Epoch:140, W1:0.6659073928174826, w2:0.3476024116512302, b:-0.8981406759222882, loss:0.6068464681996005
Epoch:141, W1:0.6655360566984204, w2:0.3467979683864498, b:-0.8999346105981036, loss:0.6061651794532416
Epoch:142, W1:0.6651721100984739, w2:0.3460070259296991, b:-0.9017113736614146, loss:0.6055070797651267
Epoch:143, W1:0.6648154455653765, w2:0.3452293818839773, b:-0.9034712124097348, loss:0.6048712560933655
Epoch:144, W1:0.6644659576714624, w2:0.3444648377184327, b:-0.9052143694992827, loss:0.6042568384366919
Epoch:145, W1:0.6641235429642088, w2:0.34371319867281247, b:-0.9069410830579399, loss:0.6036629973330521
Epoch:146, W1:0.663788099918285, w2:0.34297427366484873, b:-0.9086515867947801, loss:0.6030889415361214
Epoch:147, W1:0.663459528889053, w2:0.3422478752004748, b:-0.9103461101062935, loss:0.6025339158545785
Epoch:148, W1:0.6631377320674661, w2:0.34153381928676685, b:-0.9120248781794248, loss:0.6019971991404861
Epoch:149, W1:0.6628226134363168, w2:0.34083192534751366, b:-0.913688112091541, loss:0.6014781024144643
Epoch:150, W1:0.6625140787277842, w2:0.34014201614131834, b:-0.9153360289074369, loss:0.6009759671165273
Epoch:151, W1:0.6622120353822363, w2:0.3394639176821424, b:-0.9169688417734848, loss:0.6004901634725273
Epoch:152, W1:0.6619163925082404, w2:0.3387974591622048, b:-0.9185867600090275, loss:0.6000200889670745
Epoch:153, W1:0.6616270608437426, w2:0.33814247287715227, b:-0.920189989195113, loss:0.5995651669146583
Epoch:154, W1:0.6613439527183718, w2:0.3374987941534218, b:-0.9217787312606619, loss:0.5991248451214374
Epoch:155, W1:0.6610669820168324, w2:0.33686626127771785, b:-0.9233531845661576, loss:0.5986985946308473
Epoch:156, W1:0.660796064143346, w2:0.33624471542853085, b:-0.9249135439849439, loss:0.5982859085467755
Epoch:157, W1:0.6605311159871067, w2:0.3356340006096269, b:-0.9264600009822125, loss:0.5978863009285988
Epoch:158, W1:0.6602720558887156, w2:0.33503396358544024, b:-0.9279927436917584, loss:0.5974993057528678
Epoch:159, W1:0.660018803607562, w2:0.33444445381830396, b:-0.9295119569905794, loss:0.5971244759368651
Epoch:160, W1:0.659771280290117, w2:0.33386532340745595, b:-0.9310178225713915, loss:0.5967613824196611
Epoch:161, W1:0.6595294084391112, w2:0.33329642702976064, b:-0.9325105190131311, loss:0.5964096132966524
Epoch:162, W1:0.6592931118835669, w2:0.3327376218820883, b:-0.9339902218495092, loss:0.5960687730038985
Epoch:163, W1:0.6590623157496541, w2:0.3321887676252969, b:-0.9354571036356847, loss:0.5957384815488568
Epoch:164, W1:0.6588369464323467, w2:0.33164972632976336, b:-0.9369113340131157, loss:0.5954183737844039
Epoch:165, W1:0.6586169315678488, w2:0.33112036242241205, b:-0.9383530797726506, loss:0.5951080987232534
Epoch:166, W1:0.6584022000067696, w2:0.3306005426351928, b:-0.9397825049159154, loss:0.5948073188901245
Epoch:167, W1:0.6581926817880198, w2:0.3300901359549596, b:-0.9411997707150529, loss:0.5945157097091998
Epoch:168, W1:0.6579883081134076, w2:0.3295890135747054, b:-0.9426050357708656, loss:0.5942329589246116
Epoch:169, W1:0.6577890113229118, w2:0.32909704884610846, b:-0.9439984560694153, loss:0.5939587660518536
Epoch:170, W1:0.65759472487061, w2:0.328614117233349, b:-0.9453801850371267, loss:0.5936928418581773
Epoch:171, W1:0.6574053833012411, w2:0.32814009626815394, b:-0.946750373594444, loss:0.5934349078701682
Epoch:172, W1:0.6572209222273822, w2:0.3276748655060326, b:-0.9481091702080846, loss:0.5931846959068321
Epoch:173, W1:0.6570412783072207, w2:0.3272183064836639, b:-0.9494567209419351, loss:0.5929419476366399
Epoch:174, W1:0.6568663892229033, w2:0.32677030267739987, b:-0.9507931695066311, loss:0.5927064141570823
Epoch:175, W1:0.6566961936594424, w2:0.3263307394628501, b:-0.952118657307862, loss:0.5924778555953982
Epoch:176, W1:0.6565306312841652, w2:0.32589950407551327, b:-0.9534333234934406, loss:0.592256040729223
Epoch:177, W1:0.6563696427266864, w2:0.325476485572424, b:-0.9547373049991735, loss:0.5920407466259926
Epoch:178, W1:0.6562131695593898, w2:0.32506157479478254, b:-0.9560307365935723, loss:0.5918317583000201
Epoch:179, W1:0.6560611542784033, w2:0.3246546643315385, b:-0.9573137509214367, loss:0.5916288683862277
Epoch:180, W1:0.6559135402850514, w2:0.3242556484838982, b:-0.9585864785463472, loss:0.5914318768295925
Epoch:181, W1:0.6557702718677724, w2:0.3238644232307286, b:-0.959849047992098, loss:0.5912405905894185
Epoch:182, W1:0.655631294184484, w2:0.32348088619483, b:-0.9611015857831029, loss:0.5910548233576097
Epoch:183, W1:0.6554965532453868, w2:0.3231049366100518, b:-0.9623442164838035, loss:0.5908743952901729
Epoch:184, W1:0.6553659958961904, w2:0.32273647528922594, b:-0.9635770627371113, loss:0.5906991327512215
Epoch:185, W1:0.6552395698017504, w2:0.32237540459289377, b:-0.9648002453019099, loss:0.5905288680688074
Epoch:186, W1:0.6551172234301047, w2:0.32202162839880244, b:-0.9660138830896464, loss:0.5903634393019402
Epoch:187, W1:0.6549989060368967, w2:0.321675052072149, b:-0.9672180932000383, loss:0.5902026900182006
Epoch:188, W1:0.6548845676501744, w2:0.3213355824365492, b:-0.9684129909559207, loss:0.5900464690813856
Epoch:189, W1:0.6547741590555549, w2:0.3210031277457105, b:-0.96959868993726, loss:0.589894630448662
Epoch:190, W1:0.6546676317817426, w2:0.3206775976557889, b:-0.9707753020143568, loss:0.5897470329767317
Epoch:191, W1:0.6545649380863926, w2:0.3203589031984094, b:-0.9719429373802625, loss:0.5896035402365463
Epoch:192, W1:0.6544660309423084, w2:0.3200469567543311, b:-0.9731017045824301, loss:0.5894640203361303

(1.2213412826417385, 0.6332985435635082, -1.6265773675101587)

In [23]:
coef,intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))